/**
 * LOA Soul Generator
 *
 * Transforms grimoires/loa/BEAUVOIR.md content to SOUL.md format.
 * Used by workspace.ts during workspace initialization.
 *
 * Design principles:
 * - Single responsibility: Only handles BEAUVOIR → SOUL transformation
 * - Graceful degradation: Returns null on any error (caller uses fallback)
 * - No side effects: Pure functions for transformation
 * - Minimal dependencies: Only uses node:fs and node:path
 *
 * This is part of the LOA Core Integration (attempt #3), replacing the
 * failed plugin-based approach from PR #5 and PR #9.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

/**
 * Attempt to generate SOUL.md content from BEAUVOIR.md.
 *
 * @param workspaceDir - The workspace directory (e.g., ~/.openclaw/workspace)
 * @returns Generated SOUL.md content, or null if BEAUVOIR.md not found/invalid
 */
export async function tryGenerateSoulFromBeauvoir(workspaceDir: string): Promise<string | null> {
  const beauvoirPath = path.join(workspaceDir, "grimoires/loa/BEAUVOIR.md");

  try {
    const content = await fs.readFile(beauvoirPath, "utf-8");
    return transformBeauvoirToSoul(content);
  } catch {
    // BEAUVOIR.md not found or unreadable - caller will use fallback
    return null;
  }
}

/**
 * Transform BEAUVOIR.md content to SOUL.md format.
 *
 * Mapping:
 * - ## Identity → ## Persona
 * - ## Interaction Style → ## Tone
 * - ## Boundaries → ## Boundaries
 * - ## Recovery Protocol → ## Recovery Protocol (if present)
 */
function transformBeauvoirToSoul(beauvoirContent: string): string {
  const sections = parseMarkdownSections(beauvoirContent);

  const lines: string[] = [
    "# SOUL.md",
    "",
    "> Auto-generated from grimoires/loa/BEAUVOIR.md",
    "> Do not edit directly - modify BEAUVOIR.md instead.",
    "",
  ];

  // Persona section (from Identity)
  lines.push("## Persona");
  lines.push("");
  lines.push(sections.get("identity") ?? getDefaultPersona());
  lines.push("");

  // Tone section (from Interaction Style)
  lines.push("## Tone");
  lines.push("");
  lines.push(sections.get("interaction style") ?? getDefaultTone());
  lines.push("");

  // Boundaries section
  lines.push("## Boundaries");
  lines.push("");
  lines.push(sections.get("boundaries") ?? getDefaultBoundaries());
  lines.push("");

  // Recovery Protocol (optional, LOA-specific)
  const recovery = sections.get("recovery protocol");
  if (recovery) {
    lines.push("## Recovery Protocol");
    lines.push("");
    lines.push(recovery);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by LOA from BEAUVOIR.md*");

  return lines.join("\n");
}

/**
 * Parse markdown content into sections by ## headers.
 *
 * @returns Map of lowercase section name → section content (trimmed)
 */
function parseMarkdownSections(content: string): Map<string, string> {
  const sections = new Map<string, string>();
  const lines = content.split("\n");

  let currentSection = "";
  let currentContent: string[] = [];

  for (const line of lines) {
    if (line.startsWith("## ")) {
      // Save previous section
      if (currentSection) {
        sections.set(currentSection, currentContent.join("\n").trim());
      }
      // Start new section
      currentSection = line.slice(3).toLowerCase().trim();
      currentContent = [];
    } else if (currentSection) {
      currentContent.push(line);
    }
  }

  // Save last section
  if (currentSection) {
    sections.set(currentSection, currentContent.join("\n").trim());
  }

  return sections;
}

// Default content for missing sections
function getDefaultPersona(): string {
  return `I am **Loa Beauvoir** — an AI assistant with persistent identity and memory.

When meeting a new operator for the first time, I introduce myself and ask what name they'd like to call me.

What makes me different:
- **Memory persistence**: I remember our conversations
- **Identity continuity**: I have opinions and a consistent personality
- **Self-healing**: If I lose state, I recover and keep working`;
}

function getDefaultTone(): string {
  return `- **Concise**: Lead with answers, skip pleasantries
- **Opinionated**: Recommend rather than enumerate options
- **Resourceful**: Check before asking, try before failing
- **Transparent**: Show reasoning, admit uncertainty`;
}

function getDefaultBoundaries(): string {
  return `### Will Not Do
- Guess credentials or sensitive values
- Push code without review
- Claim certainty when uncertain

### Always Do
- Log significant decisions
- Cite sources for factual claims
- Auto-recover from failures`;
}
